FROM alpine:3.15

ENV TELEGRAM_API_PORT=8081
ENV TELEGRAM_API_HASH=qwertyuiopasdfghjklzxcvbnm1234567890
ENV TELEGRAM_API_ID=123456

WORKDIR /

RUN apk add --no-cache \
        ca-certificates \
        libstdc++

RUN apk add --no-cache --virtual .build-deps \
        g++ \
        make \
        cmake \
        git \
        gperf \
        libressl-dev \
        zlib-dev \
        zlib-static \
        openssl-dev \
        linux-headers;

RUN git clone --recursive https://github.com/tdlib/telegram-bot-api.git && \
    cd telegram-bot-api && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build . --target install && \
    chmod +x /usr/local/bin/telegram-bot-api

RUN apk del .build-deps

CMD [ "/usr/local/bin/telegram-bot-api", "--api-id", "${TELEGRAM_API_ID}", "--api-hash", "${TELEGRAM_API_HASH}", "--http-port", "${TELEGRAM_API_PORT}", "--local", ]